title: the weblog
logo: /assets/img/logo.png
show_downloads: false
theme: jekyll-theme-minimal
description: The Web does not just connect machines, it connects people.
<strong>>- Tim Berners-Lee</strong>
